added options for selecting http(s) protocol

diff --git a/src/main/bin/redwood-download b/src/main/bin/redwood-download
--- a/src/main/bin/redwood-download
+++ b/src/main/bin/redwood-download
@@ -1,24 +1,76 @@
 #!/bin/bash
 
-#
-# Usage: icgc-download.sh object-manifest output-dir
-#
-
 : "${DCC_HOME:?Need to set environment variable DCC_HOME}"
 : "${ACCESS_TOKEN:?Need to set environment variable ACCESS_TOKEN}"
 : "${REDWOOD_ENDPOINT:?Set environment variable REDWOOD_ENDPOINT to e.g. storage.ucsc-cgl.org}"
 : "${UCSC_STORAGE_TRUSTSTORE_PASSWORD:?Need to set environment variable UCSC_STORAGE_TRUSTSTORE_PASSWORD}"
 
-# config
-accessToken=${ACCESS_TOKEN}
-metadata_server_url=https://${REDWOOD_ENDPOINT}:8444
-storage_server_url=https://${REDWOOD_ENDPOINT}:5431
-trust_store_path=${DCC_HOME}/cert/clientcacerts
-trust_store_pass=${UCSC_STORAGE_TRUSTSTORE_PASSWORD}
+script_name=`basename $0`
 
-# setup
-object=$1
-download=$2
+function log {
+  logf "$1\n"
+}
 
-#download files in a manifest
-java -Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass} -Dmetadata.url=${metadata_server_url} -Dmetadata.ssl.enabled=true -Dclient.ssl.custom=false -Dstorage.url=${storage_server_url} -DaccessToken=${accessToken} -jar ${DCC_HOME}/lib/icgc-storage-client-1.0.14-SNAPSHOT/lib/icgc-storage-client.jar download --output-dir ${download} --output-layout bundle --manifest ${object} --force
+function logf {
+  if [ $dev -ne 0 ]; then
+    printf "${script_name}: $@" >&2
+  fi
+}
+
+function help {
+  cat <<EOF
+Usage: ${script_name} [-h] [-d] [-p] manifest.txt output_dir
+
+Download files via manifest from Redwood.
+
+Options
+  -h show this help message
+  -d show debug output
+  -p use http to call server; disable https
+EOF
+}
+
+
+dev=0
+http=0
+
+while getopts ":hdp" opt; do
+  case $opt in
+    h)
+      help
+      exit
+      ;;
+    d)
+      dev=1
+      log "dev mode enabled"
+      ;;
+    p)
+      http=1
+      ;;
+    \?)
+      log "Invalid option: -$OPTARG"
+      ;;
+  esac
+done
+log "running ${script_name} with http=${http}, dev=${dev}"
+
+
+function main {
+  # config
+  [[ $http -eq 1 ]] && protocol='http://' || protocol='https://'
+  accessToken=${ACCESS_TOKEN}
+  metadata_server_url=${protocol}${REDWOOD_ENDPOINT}:8444
+  storage_server_url=${protocol}${REDWOOD_ENDPOINT}:5431
+  trust_store_path=${DCC_HOME}/cert/clientcacerts
+  trust_store_pass=${UCSC_STORAGE_TRUSTSTORE_PASSWORD}
+
+  # setup
+  object=$1
+  download=$2
+
+  # download files in a manifest
+  [[ $http -eq 1 ]] && ssl_opts='' || ssl_opts='-Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass}  -Dmetadata.ssl.enabled=true -Dclient.ssl.custom=false'
+  echo java -Dmetadata.url=${metadata_server_url} -Dstorage.url=${storage_server_url} -DaccessToken=${accessToken} -jar ${DCC_HOME}/lib/icgc-storage-client-1.0.14-SNAPSHOT/lib/icgc-storage-client.jar download --output-dir ${download} --output-layout bundle --manifest ${object} --force
+}
+
+main
diff --git a/src/main/bin/spinnaker-upload b/src/main/bin/spinnaker-upload
--- a/src/main/bin/spinnaker-upload
+++ b/src/main/bin/spinnaker-upload
@@ -1,23 +1,72 @@
 #!/bin/bash
-set -x
-#
-# Usage: ucsc-upload.sh dataFile...
-#
 
 : "${DCC_HOME:?Set DCC_HOME to directory containing ucsc-storage-client}"
 : "${ACCESS_TOKEN:?Need to set environment variable ACCESS_TOKEN}"
 : "${REDWOOD_ENDPOINT:?Need to set environment variable REDWOOD_ENDPOINT to e.g. storage.ucsc-cgl.org}"
 : "${UCSC_STORAGE_TRUSTSTORE_PASSWORD:?Need to set environment variable UCSC_STORAGE_TRUSTSTORE_PASSWORD}"
 
-#config
-accessToken=${ACCESS_TOKEN}
-metadata_server_url=https://${REDWOOD_ENDPOINT}:8444
-storage_server_url=https://${REDWOOD_ENDPOINT}:5431
-tsv_file=$1
 
-#Go to the right directory and execute the script
-cd ${DCC_HOME}/dcc-spinnaker-client
-python spinnaker.py \
+script_name=`basename $0`
+
+function log {
+  logf "$1\n"
+}
+
+function logf {
+  if [ $dev -ne 0 ]; then
+    printf "${script_name}: $@" >&2
+  fi
+}
+
+function help {
+  cat <<EOF
+Usage: ${script_name} [-h] [-d] [-p] file...
+
+Upload a file to Redwood with Spinnaker
+
+Options
+  -h show this help message
+  -d show debug output
+  -p use http to call server; disable https
+EOF
+}
+
+
+dev=0
+http=0
+
+while getopts ":hdp" opt; do
+  case $opt in
+    h)
+      help
+      exit
+      ;;
+    d)
+      dev=1
+      log "dev mode enabled"
+      ;;
+    p)
+      http=1
+      ;;
+    \?)
+      log "Invalid option: -$OPTARG"
+      ;;
+  esac
+done
+log "running ${script_name} with http=${http}, dev=${dev}"
+
+
+function main {
+  # config
+  [[ $http -eq 1 ]] && protocol='http://' || protocol='https://'
+  accessToken=${ACCESS_TOKEN}
+  metadata_server_url=${protocol}${REDWOOD_ENDPOINT}:8444
+  storage_server_url=${protocol}${REDWOOD_ENDPOINT}:5431
+  tsv_file=$1
+
+  # Go to the right directory and execute the script
+  cd ${DCC_HOME}/dcc-spinnaker-client
+  echo python spinnaker.py \
     --input-metadata-schema schemas/input_metadata.json \
     --metadata-schema schemas/metadata_schema.json \
     --output-dir ../data/spinnaker/output_metadata \
@@ -26,3 +75,6 @@ python spinnaker.py \
     --force-upload \
     --storage-access-token ${ACCESS_TOKEN} \
     ${tsv_file}
+}
+
+main
diff --git a/src/main/bin/upload b/src/main/bin/upload
--- a/src/main/bin/upload
+++ b/src/main/bin/upload
@@ -1,38 +1,90 @@
 #!/bin/bash
-set -x
-#
-# Usage: ucsc-upload.sh dataFile...
-#
 
 : "${DCC_HOME:?Set DCC_HOME to directory containing ucsc-storage-client}"
 : "${ACCESS_TOKEN:?Need to set environment variable ACCESS_TOKEN}"
 : "${REDWOOD_ENDPOINT:?Need to set environment variable REDWOOD_ENDPOINT to e.g. storage.ucsc-cgl.org}"
 : "${UCSC_STORAGE_TRUSTSTORE_PASSWORD:?Need to set environment variable UCSC_STORAGE_TRUSTSTORE_PASSWORD}"
 
-# setup
-uuid=`uuidgen`
-echo using tmp dir $uuid
-upload=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`/upload/${uuid}
-manifest=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`/manifest/${uuid}
-mkdir -p ${upload}
-mkdir -p ${manifest}
-cp $* ${upload}
+script_name=`basename $0`
 
-# config
-accessToken=${ACCESS_TOKEN}
-metadata_server_url=https://${REDWOOD_ENDPOINT}:8444
-storage_server_url=https://${REDWOOD_ENDPOINT}:5431
-trust_store_path=${DCC_HOME}/cert/clientcacerts
-trust_store_pass=${UCSC_STORAGE_TRUSTSTORE_PASSWORD}
+function log {
+  logf "$1\n"
+}
 
-# register upload
-echo Registering upload:
-java -Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass} -Dserver.baseUrl=${metadata_server_url} -DaccessToken=${accessToken} -jar ${DCC_HOME}/lib/dcc-metadata-client-0.0.16-SNAPSHOT/lib/dcc-metadata-client.jar -i ${upload} -o ${manifest} -m manifest.txt
+function logf {
+  if [ $dev -ne 0 ]; then
+    printf "${script_name}: $@" >&2
+  fi
+}
 
-# perform upload
-echo Performing upload:
-java -Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass} -Dmetadata.url=${metadata_server_url} -Dmetadata.ssl.enabled=true -Dclient.ssl.custom=false -Dstorage.url=${storage_server_url} -DaccessToken=${accessToken} -jar ${DCC_HOME}/lib/icgc-storage-client-1.0.14-SNAPSHOT/lib/icgc-storage-client.jar upload --manifest ${manifest}/manifest.txt
+function help {
+  cat <<EOF
+Usage: upload [-h] [-d] [-p] file...
 
-# cleanup
-rm -r ${upload}
-rm -r ${manifest}
+For internal use only (end users use Spinnaker). Uploads individual files to Redwood.
+
+Options
+  -h show this help message
+  -d show debug output
+  -p use http to call server; disable https
+EOF
+}
+
+
+dev=0
+http=0
+
+while getopts ":hdp" opt; do
+  case $opt in
+    h)
+      help
+      exit
+      ;;
+    d)
+      dev=1
+      log "dev mode enabled"
+      ;;
+    p)
+      http=1
+      ;;
+    \?)
+      log "Invalid option: -$OPTARG"
+      ;;
+  esac
+done
+log "running ${script_name} with http=${http}, dev=${dev}"
+
+
+function main {
+  # setup
+  uuid=`uuidgen`
+  echo using tmp dir $uuid
+  upload=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`/upload/${uuid}
+  manifest=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`/manifest/${uuid}
+  mkdir -p ${upload}
+  mkdir -p ${manifest}
+  cp $* ${upload}
+
+  # config
+  [[ $http -eq 1 ]] && protocol='http://' || protocol='https://'
+  accessToken=${ACCESS_TOKEN}
+  metadata_server_url=${protocol}${REDWOOD_ENDPOINT}:8444
+  storage_server_url=${protocol}${REDWOOD_ENDPOINT}:5431
+  trust_store_path=${DCC_HOME}/cert/clientcacerts
+  trust_store_pass=${UCSC_STORAGE_TRUSTSTORE_PASSWORD}
+
+  # register upload
+  echo Registering upload:
+  java -Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass} -Dserver.baseUrl=${metadata_server_url} -DaccessToken=${accessToken} -jar ${DCC_HOME}/lib/dcc-metadata-client-0.0.16-SNAPSHOT/lib/dcc-metadata-client.jar -i ${upload} -o ${manifest} -m manifest.txt
+
+  # perform upload
+  echo Performing upload:
+  [[ $http -eq 1 ]] && ssl_opts='' || ssl_opts='-Djavax.net.ssl.trustStore=${trust_store_path} -Djavax.net.ssl.trustStorePassword=${trust_store_pass} -Dmetadata.ssl.enabled=true -Dclient.ssl.custom=false'
+  java -Dmetadata.url=${metadata_server_url} -Dstorage.url=${storage_server_url} -DaccessToken=${accessToken} ${ssl_opts} -jar ${DCC_HOME}/lib/icgc-storage-client-1.0.14-SNAPSHOT/lib/icgc-storage-client.jar upload --manifest ${manifest}/manifest.txt
+
+  # cleanup
+  rm -r ${upload}
+  rm -r ${manifest}
+}
+
+main
